config/routes.rb
Rails.application.routes.draw do
  get '/flats', to: 'flats#index'
  get '/flats/:id', to: 'flats#show', as: :flat

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController

  def index
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
  end

  def show
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
    @flat = @flats.find { |flat| flat['id'] == params[:id].to_i }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>


  <% @flats.each do |flat| %>
    <ul>
      <li>
        <%= link_to flat['name'], flat_path(flat['id'])  %>
      </li>
      <li>
        <%= flat['price'] %>
      </li>
      <li>
        <%= flat['priceCurrency'] %>
      </li>
    </ul>
  <% end %>

app/views/flats/show.html.erb
    <ul>
      <li>
        <%= @flat['name'] %>
      </li>
      <li>
        <%= @flat['price'] %>
      </li>
      <li>
        <%= @flat['priceCurrency'] %>
      </li>
    </ul>

<%= link_to 'back', flats_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Livecode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>